### ISSUE TITLE
Overlapping of the centered text

### ISSUE THREAD

**Issue by BaibhavTiwari** [thisisyashgarg/ease-it#2]
**DESCRIPTION**
The centered text on the pages are getting overlapped by the div of the texts written below it,
if you  select the text you can see the full text but as you removed the selection it gets overlapped ,

This can happen due to the improper placement of the div below it.

**IMAGES**
_The Normal _View__
![image](https://user-images.githubusercontent.com/75496387/211719129-75451828-a474-4e26-806f-63908b303e0d.png)

_On Selecting The Text_
![image](https://user-images.githubusercontent.com/75496387/211719262-a1b83ee3-a9f2-45a0-863e-70e66ce5deee.png)

**Comment by thisisyashgarg** [comment]
Thanks Baibhav, we will fix this issue asap

**Comment by BaibhavTiwari** [comment]
suree :)
